### ISSUE TITLE
min / max consumes O(n) memory

### ISSUE THREAD

**Issue by timanovsky** [numbers/numbers.js#136]
They are implemented using JS `apply()` thus copying an array into the stack frame, on large arrays it causes out of memory and crash. Easy to reproduce in nodejs.

**Comment by StDako** [comment]
I'm assuming your suggestion is to rewrite the function using a simple for-loop?

**Comment by timanovsky** [comment]
I tried very simple tests in nodejs. It looks like `reduce` is about 2X slower than `apply`; and `for` loop is 10X faster than `reduce` and 5X faster than `apply`.

**Comment by StDako** [comment]
@timanovsky what size arrays were you using? I was able to use arrays of size 10,000,000.

**Comment by timanovsky** [comment]
About 100 000. Probably it depends on node platform or version, I was
testing with 10.28 under MacOS

Best regards,
Alexey Timanovsky.

**Comment by devinjacobson** [comment]
Dont think this is an issue in this numbers library.  
min consumes no addl. memory.  Arrays should be passed as reference as in other JS engines.  
Perhaps a problem on Mac's nodejs.

**Comment by StDako** [comment]
unfortunate. nothing can be done on our end, then
