### ISSUE TITLE
New Organization!

### ISSUE THREAD

**Issue by sjkaliski** [numbers/numbers.js#137]
Hi all,

I've been speaking with @StDako and I think a great next step for numbers.js is to move this project into a new organization, [Numbers](https://github.com/numbers).

Not only will this be the new home of numbers.js, but an open space for interesting math-related libraries. The goal is for it to become a great resource for those who love (or are just becoming interested in) programming and math.

Cheers,
Steve

**Comment by StDako** [comment]
:+1: :hamburger:

**Comment by KartikTalwar** [comment]
:+1:

**Comment by sjkaliski** [comment]
We'll need a cool new logo too, @thebyrd thoughts?
