### ISSUE TITLE
standalone components

### ISSUE THREAD

**Issue by StDako** [numbers/numbers.js#139]
mentioned briefly in #113. it would be nice to be able to have each component of the repo be separate. not all users care about statistics *and* matrix operations. some questions arise:

1. do we remove the dependencies of a component? e.g. statistics depends on basic. (solution to this is to copy and paste the functions required but don't expose them to `exports`)
2. do we create a separate repository for each component?

the problem from 2) is that how do we merge all of this into one large module? I'm sure this isn't too difficult, I am just unaware of any library that does this.

**Comment by KartikTalwar** [comment]
I'm personally not in favor of this approach. I think it's already been solved by having individual files for each component and they all get compiled to `numbers.js`

**Comment by sjkaliski** [comment]
+1 @KartikTalwar

**Comment by StDako** [comment]
that's understandable. I was thinking simply for the client-side, so that the file size isn't as large.

**Comment by KartikTalwar** [comment]
`numbers.min.js` should solve that

**Comment by StDako** [comment]
:hamburger: :+1:
