### ISSUE TITLE
add section to readme about row vector format

### ISSUE THREAD

**Issue by SaintDako** [numbers/numbers.js#141]
I closed #135 because I decided to stick with the `[ [1, 0, 0] ]` way of creating row vectors instead of the `[1, 0, 0]`. that being said, we should probably add a section to the readme saying that we're using this format as it may be ambiguous.

**Comment by KartikTalwar** [comment]
I agree with your comments in #135 it should be `[[1,0,0]]`

**Comment by sjkaliski** [comment]
https://github.com/numbers/numbers.js/pull/146
