### ISSUE TITLE
Error in Documentation Link on Official NPMjs.com/packages/numbers

### ISSUE THREAD

**Issue by possnfiffer** [numbers/numbers.js#152]
Hello,

I'm reading the page https://www.npmjs.com/package/numbers where it talks about statistics.

_The statistics tools include mean, median, mode, standard deviation, random sample generator, correlation, confidence intervals, t-test, chi-square, and more._

> For further documentation, check out numbersjs.info

Consider updating it to 

> For further documentation, check out numbers.github.io

**Comment by ktamiola** [comment]
I can also confirm. Unable to connect to http://numbers.info

Perhaps, it would be more convenient to ship the package with documentation?

**Comment by boucher** [comment]
Unfortunately, to get this changed on the NPM site (and on other sites that pull from npm), you'll need to push an updated version to the npm registry.
