### ISSUE TITLE
Request to add git tag

### ISSUE THREAD

**Issue by austin665** [numbers/numbers.js#155]
@Dakkers I was trying to add this library to CDNJS based on the request here https://github.com/cdnjs/cdnjs/issues/12020  . One of the pre-requisites to add a library is to have git tags checked in.  If you could please add the git tags , I can go ahead and send a PR for cdnjs to add this lib.
Thanks!

**Comment by sjkaliski** [comment]
@austin665 https://github.com/numbers/numbers.js/releases/tag/v0.6.0

Thanks for getting this going! Let me know if there is anything else required..

**Comment by austin665** [comment]
@sjkaliski Thanks for the quick turnaround. The cdnjs PR was approved and the author will get a notification once it is added to cdnjs. Cheers!
