### ISSUE TITLE
Can we use Rational Numbers instead of the Epsilon Hack?

### ISSUE THREAD

**Issue by thebyrd** [numbers/numbers.js#46]
https://github.com/LarryBattle/Ratio.js

@sjkaliski @ethanresnick

**Comment by devinjacobson** [comment]
It depends on what you want to concentrate on for the library in general, but there will be many things you cant do without a BigNumber, or some sort of fraction/rational number engine.  i.e. I wrote a simple addition to the generator.js to generate a pascal triangle row just to play with the library, and can only get to row 55 accurately using the simple JS number precision.  If there was a "factorized" number class for working with Integers, you could get much farther for certain things like this.  
I have found the best way is to actually keep numbers in factorized rational form if you want to play with integers and go farther than what precision calculations generally takes you.  <~2^55 is quite low.  
C double gets to about 1000th row <~2^1000 with the same algorithm.  

My primary interest is for playing with integer calculations and statistics.  The library algorithms in general seem very efficient :)

generate.pascal = function (n, result) {
	if (n < 1) return;
	var s = 1;
	var stemp = 1;
	var ntemp = n;
	result.push(s);
	while (ntemp > 0){
		s *= ntemp--;
		s /= stemp++;
		s = Math.round(s);
		result.push(s);
	}
	return;
};
